### ISSUE TITLE
Reasoning for memoization?

### ISSUE THREAD

**Issue by leomosley** [GetWorkTools/support-docs-ai#11]
Why are all components and pages wrapped in `memo` . Server components are not re-rendered on the client so there is no reason for them to be wrapped in `memo`.  

Can I know the reasoning behind it? I might be missing something.

**Comment by Moniv9** [comment]
Using `memo` helps in avoiding re-rendering if the props are same. And as we are using decent enough interactions and consuming realtime data, it will be helpful to memoize components.
Also there is not much harm in memoizing everything if there is decent enough interactions in the app.

To read more about this, can follow this Github issue thread.
https://github.com/facebook/react/issues/14463#issuecomment-1657065155

Note: When we migrate to React 19 in future, then we might not need this.

**Comment by Moniv9** [comment]
@leomosley, let me know if you need more explanation. Else will close this issue by tomorrow.

**Comment by leomosley** [comment]
All good, can be closed now
