### ISSUE TITLE
Production down?

### ISSUE THREAD

**Issue by leomosley** [GetWorkTools/support-docs-ai#20]
Getting "404 : NOT_FOUND" when trying to access https://supportdocs.getworktools.com/.

Not sure if this is an error in prod or a vercel issue.  

![image](https://github.com/user-attachments/assets/4191c806-0864-4e6b-b608-42fcb7d20943)

**Comment by Moniv9** [comment]
Exhausted my hobby account limits on versel, so need to turn it off.
